"""add required phone_number and optional apt_num

Revision ID: 749060d0a1aa
Revises: b95fbf8bcd87
Create Date: 2025-11-11 23:52:19.225092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '749060d0a1aa'
down_revision: Union[str, Sequence[str], None] = 'b95fbf8bcd87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
