"""fix address relationships

Revision ID: b95fbf8bcd87
Revises: 8717fa1603f1
Create Date: 2025-11-11 22:56:59.789417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b95fbf8bcd87'
down_revision: Union[str, Sequence[str], None] = '8717fa1603f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address', 'address1',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('address', 'address2',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('address', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('address', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('address', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('address', 'postalcode',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_address_id'), 'address', ['id'], unique=False)
    op.drop_constraint(op.f('address_users_fk'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'address', ['address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('address_users_fk'), 'users', 'address', ['address_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_address_id'), table_name='address')
    op.alter_column('address', 'postalcode',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('address', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('address', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('address', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('address', 'address2',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('address', 'address1',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
